### ISSUE TITLE
我想知道怎么把头像改成自己的

### ISSUE THREAD

**Issue by xigrug** [xzy256/xzy-resume#1]
直接点击图片输入链接确定后，保存index.html后还是不能更改头像.然后就是这个模板的画布大小能不能修改，我发现内容多了后放不下，另外还有些地方自动换行了

**Comment by xzy256** [comment]
>直接点击图片输入链接确定后，保存index.html后还是不能更改头像

修改配置文件 static/css/style.css下面的这个URL地址，头像图片必须是一个URL地址的图片，像我是我的github头像的地址。你也可以将图片存储在文件image下，把这个设置成相对路径，都是可以显示的。
`background-image:url`
>画布大小问题

这个网页模板我也是用别人的，HTML不太熟悉，当时自己弄的时候费了很大的劲进行版面适配，建议你在github页直接修改，查看生成的效果，结合浏览器看源码的方式，找到不适配的地方，进行修改。抱歉，这个我帮不了太大忙
